/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProgramAgenda {}
  interface AppProgramAgendaAttributes extends StencilHTMLAttributes {}

  interface AppProgramTalkDetail {
    'match': MatchResults;
  }
  interface AppProgramTalkDetailAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppProgram {}
  interface AppProgramAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppHeader {}
  interface AppHeaderAttributes extends StencilHTMLAttributes {}

  interface AppLoader {}
  interface AppLoaderAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProgramAgenda': Components.AppProgramAgenda;
    'AppProgramTalkDetail': Components.AppProgramTalkDetail;
    'AppProgram': Components.AppProgram;
    'AppRoot': Components.AppRoot;
    'AppHeader': Components.AppHeader;
    'AppLoader': Components.AppLoader;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-program-agenda': Components.AppProgramAgendaAttributes;
    'app-program-talk-detail': Components.AppProgramTalkDetailAttributes;
    'app-program': Components.AppProgramAttributes;
    'app-root': Components.AppRootAttributes;
    'app-header': Components.AppHeaderAttributes;
    'app-loader': Components.AppLoaderAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProgramAgendaElement extends Components.AppProgramAgenda, HTMLStencilElement {}
  var HTMLAppProgramAgendaElement: {
    prototype: HTMLAppProgramAgendaElement;
    new (): HTMLAppProgramAgendaElement;
  };

  interface HTMLAppProgramTalkDetailElement extends Components.AppProgramTalkDetail, HTMLStencilElement {}
  var HTMLAppProgramTalkDetailElement: {
    prototype: HTMLAppProgramTalkDetailElement;
    new (): HTMLAppProgramTalkDetailElement;
  };

  interface HTMLAppProgramElement extends Components.AppProgram, HTMLStencilElement {}
  var HTMLAppProgramElement: {
    prototype: HTMLAppProgramElement;
    new (): HTMLAppProgramElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppLoaderElement extends Components.AppLoader, HTMLStencilElement {}
  var HTMLAppLoaderElement: {
    prototype: HTMLAppLoaderElement;
    new (): HTMLAppLoaderElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-program-agenda': HTMLAppProgramAgendaElement
    'app-program-talk-detail': HTMLAppProgramTalkDetailElement
    'app-program': HTMLAppProgramElement
    'app-root': HTMLAppRootElement
    'app-header': HTMLAppHeaderElement
    'app-loader': HTMLAppLoaderElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-program-agenda': HTMLAppProgramAgendaElement;
    'app-program-talk-detail': HTMLAppProgramTalkDetailElement;
    'app-program': HTMLAppProgramElement;
    'app-root': HTMLAppRootElement;
    'app-header': HTMLAppHeaderElement;
    'app-loader': HTMLAppLoaderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
